/* Generated By:JavaCC: Do not edit this line. LRPConstants.java */
package uniandes.teolen.parserJavaCC.LRP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LRPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VALUE = 5;
  /** RegularExpression Id. */
  int TIME = 6;
  /** RegularExpression Id. */
  int PROOF = 7;
  /** RegularExpression Id. */
  int CONSTANT = 8;
  /** RegularExpression Id. */
  int NAME = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<VALUE>",
    "<TIME>",
    "<PROOF>",
    "<CONSTANT>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"spawn\"",
    "\"(var\"",
    "\":=[\"",
    "\" ])\"",
    "\"(machine\"",
    "\")\"",
    "\"(on\"",
    "\"- >\"",
    "\"(ontime\"",
    "\"*- >\"",
    "\"(event\"",
    "\"[\"",
    "\"]\"",
    "\"(state\"",
    "\"(onentry\"",
    "\"(onexit\"",
    "\"(running\"",
  };

}
