/* Generated By:JavaCC: Do not edit this line. LRPConstants.java */
package uniandes.teolen.parserJavaCC.LRP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LRPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPAWN = 5;
  /** RegularExpression Id. */
  int FLECHA = 6;
  /** RegularExpression Id. */
  int WILD = 7;
  /** RegularExpression Id. */
  int ONTIME = 8;
  /** RegularExpression Id. */
  int ON = 9;
  /** RegularExpression Id. */
  int M = 10;
  /** RegularExpression Id. */
  int VALUE = 11;
  /** RegularExpression Id. */
  int TIME = 12;
  /** RegularExpression Id. */
  int PROOF = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;
  /** RegularExpression Id. */
  int NAME = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"spawn\"",
    "\"->\"",
    "\"*->\"",
    "\"(ontime\"",
    "\"(on\"",
    "\"(machine\"",
    "<VALUE>",
    "<TIME>",
    "<PROOF>",
    "<CONSTANT>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(var\"",
    "\":=[\"",
    "\" ])\"",
    "\")\"",
    "\"(event\"",
    "\"[\"",
    "\"]\"",
    "\"(state\"",
    "\"(onentry\"",
    "\"(onexit\"",
    "\"(running\"",
  };

}
